In [1]:
# Importação de bibliotecas
import pandas as pd
import numpy as np

In [2]:
arquivo = "PRO-009-25_REV 1 - PROPOSTA COMERCIAL.xlsx" # nome do arquivo

aba = "CPU 1 " # aba = "CPU 1" # nome da aba

In [3]:
# Consumindo os dados
meta = pd.read_excel("PRO-009-25_REV 1 - PROPOSTA COMERCIAL.xlsx", sheet_name="CPU  1 ", nrows=2, header=None)

df = pd.read_excel("PRO-009-25_REV 1 - PROPOSTA COMERCIAL.xlsx", sheet_name="CPU  1 ", skiprows=5)

c:\Users\anderson.marley\AppData\Local\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():
c:\Users\anderson.marley\AppData\Local\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

In [4]:
# Buscando as colunas
df.columns = df.columns.map(str)

# Visualizando
df.columns

Index(['Unnamed: 0', 'Cód.', 'Discriminação', 'Unid', 'P.Unit', 'Quant',
       'F.utiliz', 'Custo', 'Quant.1', 'F.utiliz.1',
       ...
       'F.utiliz.36', 'Custo.36', 'Quant.37', 'F.utiliz.37', 'Custo.37',
       'Unnamed: 119', 'Quant.38', 'F.utiliz.38', 'Custo.38', 'Unnamed: 123'],
      dtype='object', length=124)

In [5]:
# Selecionando as colunas
lista = ['Unnamed: 0', 'Cód.', 'Discriminação', 'Unid', 'Unnamed: 123']

# Percorrendo as colunas e convertendo os tipos
for i in df.columns:
    
    # Checando se a coluna está na lista e Se estiver, converte para string, caso contrário, converte para numérico
    if i in lista:
        # Convertendo para string
        df[i] = df[i].astype(str)
        
    else:
        # Convertendo para numérico e arredondando
        df[i] = pd.to_numeric(df[i], errors='coerce').round(2)

In [6]:
#col_base = ['Cód.', 'Discriminação', 'Unid', 'P.Unit']

In [7]:
# Removando os NaN das colunas ...
df = df.dropna(subset=['Unid', 'P.Unit'])

In [8]:
# Alterando os dados NaN
df = df.fillna(0).round(2)

In [9]:
# Selecionando colunas bases
col_base = ['Cód.', 'Discriminação', 'Unid', 'P.Unit']

# Selecionando a partir da 5 coluna
col_inicial = 5

# Calcula o total de colunas do DF
col_total = len(df.columns)

# Elemina as colunas inicias e divide por 3 assumindo que cada grupo tem 3 colunas.
num_grupos = (col_total - col_inicial) // 3

In [10]:
# Criando tabela para composições
tabelas_composicoes = []

In [11]:
for i in range(num_grupos):

    # Calcula o indice atual, apos 'col_inicial'
    idx = col_inicial + i * 3
    
    # Pega a coluna da composição
    identificador = str(meta.iloc[0, idx]).strip()
    # Pega o nome da composição
    nome = str(meta.iloc[1, idx]).strip()
    
    # Pega os nomes das colunas
    col_quant = df.columns[idx]
    col_futiliz = df.columns[idx + 1]
    col_custo = df.columns[idx + 2]
    
    # Monta o bloco
    bloco = df[col_base + [col_quant, col_futiliz, col_custo]].copy()
    bloco.columns = col_base + ['Quant', 'Futiliz', 'Custo']
    bloco['Composicao'] = nome
    bloco['Identificador'] = identificador
    
    # Filtra apenas linhas relevantes (com valor em Quant ou Custo)
    bloco = bloco.dropna(subset=['Quant', 'Custo'], how='all')
    
    # Adiciona à lista final
    tabelas_composicoes.append(bloco)

In [12]:
# Concatenando todas as tabelas de composições
df_final = pd.concat(tabelas_composicoes, ignore_index=True)

In [13]:
# Organiza colunas
df_final = df_final[
    ['Cód.', 'Discriminação', 'Unid', 'P.Unit', 'Quant', 'Futiliz', 'Custo', 'Composicao']
]

In [14]:
# Exibe cada composição separadamente no Jupyter
composicoes_unicas = df_final['Composicao'].dropna().unique()

In [15]:
for comp in composicoes_unicas:
    print(f"\n🔹 Tabela: {comp}\n")

    # Filtra a composição atual
    tabela = df_final[df_final['Composicao'] == comp].copy()

    # Garante que a coluna 'Cód.' seja tratada corretamente
    cod_col = tabela['Cód.'].astype(str).str.strip().replace({'nan': np.nan, '': np.nan})

    # Encontra o primeiro índice onde 'Cód.' é NaN
    idx_nan = cod_col[cod_col.isna()].index

    # Se houver linha com NaN em 'Cód.', remove tudo a partir dela
    if not idx_nan.empty:
        tabela = tabela.loc[:idx_nan[0] - 1]

    # Exibe a tabela limpa
    display(tabela.reset_index(drop=True))

🔹 Tabela: Mobilização

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,160.0,1.00,4804.36,Mobilização
1,P02,Eletricista de força e controle,hh,35.64,160.0,1.00,5702.30,Mobilização
2,P03,Ajudante de elétrica,hh,21.21,160.0,2.00,6787.80,Mobilização
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.00,0.00,Mobilização
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.00,0.00,Mobilização
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Mobilização
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,160.0,1.00,5546.75,Mobilização
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,160.0,1.00,6806.18,Mobilização
8,P09,Montador de estruturas metálicas,hh,30.15,160.0,1.00,4823.26,Mobilização
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Mobilização
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Mobilização
11,P12,Sinaleiro de rigger,hh,21.89,160.0,1.00,3502.06,Mobilização
12,P13,Servente/Auxiliar de obras,hh,15.72,160.0,2.00,5031.13,Mobilização
13,P14,Supervisor de obras,hh,52.05,160.0,1.00,8327.56,Mobilização
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Mobilização
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Mobilização
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Mobilização
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Mobilização
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Mobilização
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Mobilização
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Mobilização
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Mobilização
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Mobilização
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Mobilização
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Mobilização
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Mobilização
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Mobilização
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Mobilização
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Mobilização
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Mobilização
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Mobilização
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Mobilização
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Mobilização
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Mobilização
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Mobilização
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Mobilização
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Mobilização
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Mobilização
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Mobilização
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Mobilização
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Mobilização
41,O01,ART,Vb,271.52,1.0,1.00,271.52,Mobilização
42,O02,Exames médicos,Vb,456.00,11.0,0.50,2508.00,Mobilização
43,O03,Treinamentos,Vb,426.00,11.0,1.00,4686.00,Mobilização
44,O04,Plano de saúde,Vb/mês,254.10,11.0,0.91,2541.00,Mobilização
45,O05,Cesta básica,Vb/mês,326.13,11.0,0.91,3261.30,Mobilização
46,O06,Seguro profissional,Vb/mês,12.55,11.0,0.91,125.50,Mobilização
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,11.0,0.91,1210.00,Mobilização
48,O08,Alimentação - Almoço,Vb/mês,440.00,11.0,0.91,4400.00,Mobilização
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,11.0,0.91,1152.00,Mobilização
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Mobilização
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Mobilização
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Mobilização
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Mobilização

🔹 Tabela: Desmobilização

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,80.0,1.00,2402.18,Desmobilização
1,P02,Eletricista de força e controle,hh,35.64,80.0,1.00,2851.15,Desmobilização
2,P03,Ajudante de elétrica,hh,21.21,80.0,2.00,3393.90,Desmobilização
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.00,0.00,Desmobilização
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.00,0.00,Desmobilização
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Desmobilização
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,80.0,1.00,2773.37,Desmobilização
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,80.0,1.00,3403.09,Desmobilização
8,P09,Montador de estruturas metálicas,hh,30.15,80.0,1.00,2411.63,Desmobilização
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Desmobilização
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Desmobilização
11,P12,Sinaleiro de rigger,hh,21.89,80.0,1.00,1751.03,Desmobilização
12,P13,Servente/Auxiliar de obras,hh,15.72,80.0,2.00,2515.56,Desmobilização
13,P14,Supervisor de obras,hh,52.05,80.0,1.00,4163.78,Desmobilização
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Desmobilização
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Desmobilização
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Desmobilização
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Desmobilização
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Desmobilização
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Desmobilização
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Desmobilização
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Desmobilização
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Desmobilização
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Desmobilização
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Desmobilização
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Desmobilização
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Desmobilização
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Desmobilização
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Desmobilização
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Desmobilização
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Desmobilização
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Desmobilização
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Desmobilização
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Desmobilização
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Desmobilização
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Desmobilização
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Desmobilização
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Desmobilização
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Desmobilização
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Desmobilização
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Desmobilização
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Desmobilização
42,O02,Exames médicos,Vb,456.00,11.0,0.50,2508.00,Desmobilização
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Desmobilização
44,O04,Plano de saúde,Vb/mês,254.10,11.0,0.45,1270.50,Desmobilização
45,O05,Cesta básica,Vb/mês,326.13,11.0,0.45,1630.65,Desmobilização
46,O06,Seguro profissional,Vb/mês,12.55,11.0,0.45,62.75,Desmobilização
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,11.0,0.45,605.00,Desmobilização
48,O08,Alimentação - Almoço,Vb/mês,440.00,11.0,0.45,2200.00,Desmobilização
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,11.0,0.45,576.00,Desmobilização
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Desmobilização
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Desmobilização
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Desmobilização
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Desmobilização

🔹 Tabela: Canteiro de Obras

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.0,0.00,0.00,Canteiro de Obras
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.00,0.00,Canteiro de Obras
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.00,0.00,Canteiro de Obras
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.00,0.00,Canteiro de Obras
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.00,0.00,Canteiro de Obras
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Canteiro de Obras
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.00,0.00,Canteiro de Obras
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.0,0.00,0.00,Canteiro de Obras
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.00,0.00,Canteiro de Obras
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Canteiro de Obras
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Canteiro de Obras
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.00,0.00,Canteiro de Obras
12,P13,Servente/Auxiliar de obras,hh,15.72,80.0,2.00,2515.56,Canteiro de Obras
13,P14,Supervisor de obras,hh,52.05,0.0,0.00,0.00,Canteiro de Obras
14,E01,Conteiner escritório,Vb/mês,1700.00,1.0,1.32,2240.91,Canteiro de Obras
15,E02,Banheiro químico,Vb/mês,1200.00,1.0,1.32,1581.82,Canteiro de Obras
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,1.0,1.00,4500.00,Canteiro de Obras
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,1.0,1.00,852.46,Canteiro de Obras
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Canteiro de Obras
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Canteiro de Obras
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Canteiro de Obras
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Canteiro de Obras
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Canteiro de Obras
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Canteiro de Obras
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Canteiro de Obras
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Canteiro de Obras
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Canteiro de Obras
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Canteiro de Obras
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Canteiro de Obras
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Canteiro de Obras
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Canteiro de Obras
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Canteiro de Obras
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Canteiro de Obras
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Canteiro de Obras
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Canteiro de Obras
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Canteiro de Obras
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Canteiro de Obras
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Canteiro de Obras
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Canteiro de Obras
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Canteiro de Obras
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Canteiro de Obras
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Canteiro de Obras
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Canteiro de Obras
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Canteiro de Obras
44,O04,Plano de saúde,Vb/mês,254.10,0.0,0.00,0.00,Canteiro de Obras
45,O05,Cesta básica,Vb/mês,326.13,0.0,0.00,0.00,Canteiro de Obras
46,O06,Seguro profissional,Vb/mês,12.55,0.0,0.00,0.00,Canteiro de Obras
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.0,0.00,0.00,Canteiro de Obras
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.0,0.00,0.00,Canteiro de Obras
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.0,0.00,0.00,Canteiro de Obras
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Canteiro de Obras
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Canteiro de Obras
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Canteiro de Obras
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Canteiro de Obras

🔹 Tabela: Comissionamento e Start Up

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.0,0.00,0.00,Comissionamento e Start Up
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.00,0.00,Comissionamento e Start Up
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.00,0.00,Comissionamento e Start Up
3,P04,Engenheiro eletricista,hh,122.13,112.0,1.00,13678.66,Comissionamento e Start Up
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.00,0.00,Comissionamento e Start Up
5,P06,Projetista (Cadista),hh,28.53,112.0,1.00,3194.90,Comissionamento e Start Up
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.00,0.00,Comissionamento e Start Up
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.0,0.00,0.00,Comissionamento e Start Up
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.00,0.00,Comissionamento e Start Up
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Comissionamento e Start Up
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Comissionamento e Start Up
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.00,0.00,Comissionamento e Start Up
12,P13,Servente/Auxiliar de obras,hh,15.72,0.0,0.00,0.00,Comissionamento e Start Up
13,P14,Supervisor de obras,hh,52.05,0.0,0.00,0.00,Comissionamento e Start Up
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Comissionamento e Start Up
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Comissionamento e Start Up
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Comissionamento e Start Up
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Comissionamento e Start Up
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Comissionamento e Start Up
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Comissionamento e Start Up
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Comissionamento e Start Up
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Comissionamento e Start Up
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Comissionamento e Start Up
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Comissionamento e Start Up
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Comissionamento e Start Up
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Comissionamento e Start Up
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Comissionamento e Start Up
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Comissionamento e Start Up
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Comissionamento e Start Up
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Comissionamento e Start Up
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Comissionamento e Start Up
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Comissionamento e Start Up
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Comissionamento e Start Up
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Comissionamento e Start Up
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Comissionamento e Start Up
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Comissionamento e Start Up
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Comissionamento e Start Up
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Comissionamento e Start Up
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Comissionamento e Start Up
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Comissionamento e Start Up
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Comissionamento e Start Up
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Comissionamento e Start Up
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Comissionamento e Start Up
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Comissionamento e Start Up
44,O04,Plano de saúde,Vb/mês,254.10,0.0,0.00,0.00,Comissionamento e Start Up
45,O05,Cesta básica,Vb/mês,326.13,0.0,0.00,0.00,Comissionamento e Start Up
46,O06,Seguro profissional,Vb/mês,12.55,0.0,0.00,0.00,Comissionamento e Start Up
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.0,0.00,0.00,Comissionamento e Start Up
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.0,0.00,0.00,Comissionamento e Start Up
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.0,0.00,0.00,Comissionamento e Start Up
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Comissionamento e Start Up
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Comissionamento e Start Up
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Comissionamento e Start Up
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Comissionamento e Start Up

🔹 Tabela: Databook

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.0,0.00,0.00,Databook
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.00,0.00,Databook
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.00,0.00,Databook
3,P04,Engenheiro eletricista,hh,122.13,56.0,1.00,6839.33,Databook
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.00,0.00,Databook
5,P06,Projetista (Cadista),hh,28.53,56.0,1.00,1597.45,Databook
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.00,0.00,Databook
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.0,0.00,0.00,Databook
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.00,0.00,Databook
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Databook
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Databook
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.00,0.00,Databook
12,P13,Servente/Auxiliar de obras,hh,15.72,0.0,0.00,0.00,Databook
13,P14,Supervisor de obras,hh,52.05,0.0,0.00,0.00,Databook
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Databook
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Databook
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Databook
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Databook
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Databook
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Databook
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Databook
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Databook
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Databook
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Databook
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Databook
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Databook
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Databook
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Databook
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Databook
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Databook
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Databook
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Databook
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Databook
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Databook
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Databook
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Databook
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Databook
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Databook
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Databook
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Databook
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Databook
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Databook
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Databook
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Databook
44,O04,Plano de saúde,Vb/mês,254.10,0.0,0.00,0.00,Databook
45,O05,Cesta básica,Vb/mês,326.13,0.0,0.00,0.00,Databook
46,O06,Seguro profissional,Vb/mês,12.55,0.0,0.00,0.00,Databook
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.0,0.00,0.00,Databook
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.0,0.00,0.00,Databook
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.0,0.00,0.00,Databook
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Databook
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Databook
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Databook
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Databook

🔹 Tabela: Levantamento de Campo

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.0,0.00,0.00,Levantamento de Campo
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.00,0.00,Levantamento de Campo
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.00,0.00,Levantamento de Campo
3,P04,Engenheiro eletricista,hh,122.13,24.0,1.00,2931.14,Levantamento de Campo
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,24.0,1.00,2931.14,Levantamento de Campo
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Levantamento de Campo
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.00,0.00,Levantamento de Campo
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.0,0.00,0.00,Levantamento de Campo
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.00,0.00,Levantamento de Campo
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Levantamento de Campo
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Levantamento de Campo
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.00,0.00,Levantamento de Campo
12,P13,Servente/Auxiliar de obras,hh,15.72,0.0,0.00,0.00,Levantamento de Campo
13,P14,Supervisor de obras,hh,52.05,0.0,0.00,0.00,Levantamento de Campo
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Levantamento de Campo
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Levantamento de Campo
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Levantamento de Campo
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Levantamento de Campo
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Levantamento de Campo
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Levantamento de Campo
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Levantamento de Campo
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Levantamento de Campo
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Levantamento de Campo
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Levantamento de Campo
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Levantamento de Campo
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Levantamento de Campo
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Levantamento de Campo
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Levantamento de Campo
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Levantamento de Campo
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Levantamento de Campo
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Levantamento de Campo
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Levantamento de Campo
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Levantamento de Campo
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Levantamento de Campo
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Levantamento de Campo
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Levantamento de Campo
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Levantamento de Campo
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Levantamento de Campo
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Levantamento de Campo
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Levantamento de Campo
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Levantamento de Campo
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Levantamento de Campo
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Levantamento de Campo
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Levantamento de Campo
44,O04,Plano de saúde,Vb/mês,254.10,0.0,0.00,0.00,Levantamento de Campo
45,O05,Cesta básica,Vb/mês,326.13,0.0,0.00,0.00,Levantamento de Campo
46,O06,Seguro profissional,Vb/mês,12.55,0.0,0.00,0.00,Levantamento de Campo
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.0,0.00,0.00,Levantamento de Campo
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.0,0.00,0.00,Levantamento de Campo
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.0,0.00,0.00,Levantamento de Campo
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Levantamento de Campo
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Levantamento de Campo
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Levantamento de Campo
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Levantamento de Campo

🔹 Tabela: Topografia

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.0,0.00,0.00,Topografia
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.00,0.00,Topografia
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.00,0.00,Topografia
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.00,0.00,Topografia
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.00,0.00,Topografia
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Topografia
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.00,0.00,Topografia
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.0,0.00,0.00,Topografia
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.00,0.00,Topografia
9,P10,Topógrafo,hh,31.03,80.0,1.00,2482.25,Topografia
10,P11,Auxiliar de topografia,hh,16.52,80.0,1.00,1321.20,Topografia
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.00,0.00,Topografia
12,P13,Servente/Auxiliar de obras,hh,15.72,0.0,0.00,0.00,Topografia
13,P14,Supervisor de obras,hh,52.05,0.0,0.00,0.00,Topografia
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Topografia
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Topografia
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Topografia
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Topografia
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Topografia
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,1.0,0.45,125.00,Topografia
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,1.0,0.45,568.18,Topografia
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,1.0,0.45,795.45,Topografia
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Topografia
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Topografia
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Topografia
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Topografia
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Topografia
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Topografia
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Topografia
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Topografia
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Topografia
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Topografia
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Topografia
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Topografia
34,M11,Estaca de madeira,und,5.00,25.0,1.00,125.00,Topografia
35,M12,Piquete de madeira,und,3.50,15.0,1.00,52.50,Topografia
36,M13,Tinta - 18L,und,260.00,1.0,1.00,260.00,Topografia
37,M14,Marcador Industrial,und,16.50,2.0,1.00,33.00,Topografia
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Topografia
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Topografia
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Topografia
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Topografia
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Topografia
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Topografia
44,O04,Plano de saúde,Vb/mês,254.10,0.0,0.00,0.00,Topografia
45,O05,Cesta básica,Vb/mês,326.13,0.0,0.00,0.00,Topografia
46,O06,Seguro profissional,Vb/mês,12.55,0.0,0.00,0.00,Topografia
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.0,0.00,0.00,Topografia
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.0,0.00,0.00,Topografia
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.0,0.00,0.00,Topografia
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Topografia
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Topografia
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Topografia
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Topografia

🔹 Tabela: Lista de Desenhos e Documentos (LDD)

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
3,P04,Engenheiro eletricista,hh,122.13,40.0,0.40,1954.09,Lista de Desenhos e Documentos (LDD)
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,40.0,0.60,2931.14,Lista de Desenhos e Documentos (LDD)
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
12,P13,Servente/Auxiliar de obras,hh,15.72,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
13,P14,Supervisor de obras,hh,52.05,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Lista de Desenhos e Documentos (LDD)
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
44,O04,Plano de saúde,Vb/mês,254.10,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
45,O05,Cesta básica,Vb/mês,326.13,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
46,O06,Seguro profissional,Vb/mês,12.55,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Lista de Desenhos e Documentos (LDD)

🔹 Tabela: Memorial de Cálculo

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.0,0.00,0.00,Memorial de Cálculo
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.00,0.00,Memorial de Cálculo
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.00,0.00,Memorial de Cálculo
3,P04,Engenheiro eletricista,hh,122.13,40.0,0.50,2442.62,Memorial de Cálculo
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,40.0,0.50,2442.62,Memorial de Cálculo
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Memorial de Cálculo
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.00,0.00,Memorial de Cálculo
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.0,0.00,0.00,Memorial de Cálculo
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.00,0.00,Memorial de Cálculo
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Memorial de Cálculo
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Memorial de Cálculo
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.00,0.00,Memorial de Cálculo
12,P13,Servente/Auxiliar de obras,hh,15.72,0.0,0.00,0.00,Memorial de Cálculo
13,P14,Supervisor de obras,hh,52.05,0.0,0.00,0.00,Memorial de Cálculo
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Memorial de Cálculo
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Memorial de Cálculo
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Memorial de Cálculo
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Memorial de Cálculo
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Memorial de Cálculo
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Memorial de Cálculo
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Memorial de Cálculo
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Memorial de Cálculo
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Memorial de Cálculo
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Memorial de Cálculo
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Memorial de Cálculo
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Memorial de Cálculo
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Memorial de Cálculo
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Memorial de Cálculo
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Memorial de Cálculo
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Memorial de Cálculo
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Memorial de Cálculo
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Memorial de Cálculo
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Memorial de Cálculo
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Memorial de Cálculo
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Memorial de Cálculo
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Memorial de Cálculo
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Memorial de Cálculo
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Memorial de Cálculo
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Memorial de Cálculo
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Memorial de Cálculo
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Memorial de Cálculo
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Memorial de Cálculo
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Memorial de Cálculo
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Memorial de Cálculo
44,O04,Plano de saúde,Vb/mês,254.10,0.0,0.00,0.00,Memorial de Cálculo
45,O05,Cesta básica,Vb/mês,326.13,0.0,0.00,0.00,Memorial de Cálculo
46,O06,Seguro profissional,Vb/mês,12.55,0.0,0.00,0.00,Memorial de Cálculo
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.0,0.00,0.00,Memorial de Cálculo
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.0,0.00,0.00,Memorial de Cálculo
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.0,0.00,0.00,Memorial de Cálculo
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Memorial de Cálculo
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Memorial de Cálculo
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Memorial de Cálculo
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Memorial de Cálculo

🔹 Tabela: Especificação Técnica dos Perfis

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.0,0.00,0.00,Especificação Técnica dos Perfis
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.00,0.00,Especificação Técnica dos Perfis
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.00,0.00,Especificação Técnica dos Perfis
3,P04,Engenheiro eletricista,hh,122.13,40.0,0.10,488.52,Especificação Técnica dos Perfis
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,40.0,0.90,4396.71,Especificação Técnica dos Perfis
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Especificação Técnica dos Perfis
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.00,0.00,Especificação Técnica dos Perfis
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.0,0.00,0.00,Especificação Técnica dos Perfis
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.00,0.00,Especificação Técnica dos Perfis
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Especificação Técnica dos Perfis
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Especificação Técnica dos Perfis
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.00,0.00,Especificação Técnica dos Perfis
12,P13,Servente/Auxiliar de obras,hh,15.72,0.0,0.00,0.00,Especificação Técnica dos Perfis
13,P14,Supervisor de obras,hh,52.05,0.0,0.00,0.00,Especificação Técnica dos Perfis
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Especificação Técnica dos Perfis
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Especificação Técnica dos Perfis
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Especificação Técnica dos Perfis
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Especificação Técnica dos Perfis
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Especificação Técnica dos Perfis
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Especificação Técnica dos Perfis
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Especificação Técnica dos Perfis
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Especificação Técnica dos Perfis
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Especificação Técnica dos Perfis
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Especificação Técnica dos Perfis
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Especificação Técnica dos Perfis
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Especificação Técnica dos Perfis
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Especificação Técnica dos Perfis
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Especificação Técnica dos Perfis
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Especificação Técnica dos Perfis
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Especificação Técnica dos Perfis
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Especificação Técnica dos Perfis
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Especificação Técnica dos Perfis
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Especificação Técnica dos Perfis
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Especificação Técnica dos Perfis
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Especificação Técnica dos Perfis
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Especificação Técnica dos Perfis
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Especificação Técnica dos Perfis
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Especificação Técnica dos Perfis
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Especificação Técnica dos Perfis
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Especificação Técnica dos Perfis
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Especificação Técnica dos Perfis
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Especificação Técnica dos Perfis
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Especificação Técnica dos Perfis
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Especificação Técnica dos Perfis
44,O04,Plano de saúde,Vb/mês,254.10,0.0,0.00,0.00,Especificação Técnica dos Perfis
45,O05,Cesta básica,Vb/mês,326.13,0.0,0.00,0.00,Especificação Técnica dos Perfis
46,O06,Seguro profissional,Vb/mês,12.55,0.0,0.00,0.00,Especificação Técnica dos Perfis
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.0,0.00,0.00,Especificação Técnica dos Perfis
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.0,0.00,0.00,Especificação Técnica dos Perfis
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.0,0.00,0.00,Especificação Técnica dos Perfis
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Especificação Técnica dos Perfis
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Especificação Técnica dos Perfis
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Especificação Técnica dos Perfis
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Especificação Técnica dos Perfis

🔹 Tabela: Planilha de Quantidades (PQ)

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.0,0.00,0.00,Planilha de Quantidades (PQ)
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.00,0.00,Planilha de Quantidades (PQ)
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.00,0.00,Planilha de Quantidades (PQ)
3,P04,Engenheiro eletricista,hh,122.13,40.0,0.55,2686.88,Planilha de Quantidades (PQ)
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,40.0,0.45,2198.36,Planilha de Quantidades (PQ)
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Planilha de Quantidades (PQ)
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.00,0.00,Planilha de Quantidades (PQ)
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.0,0.00,0.00,Planilha de Quantidades (PQ)
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.00,0.00,Planilha de Quantidades (PQ)
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Planilha de Quantidades (PQ)
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Planilha de Quantidades (PQ)
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.00,0.00,Planilha de Quantidades (PQ)
12,P13,Servente/Auxiliar de obras,hh,15.72,0.0,0.00,0.00,Planilha de Quantidades (PQ)
13,P14,Supervisor de obras,hh,52.05,0.0,0.00,0.00,Planilha de Quantidades (PQ)
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Planilha de Quantidades (PQ)
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Planilha de Quantidades (PQ)
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Planilha de Quantidades (PQ)
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Planilha de Quantidades (PQ)
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Planilha de Quantidades (PQ)
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Planilha de Quantidades (PQ)
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Planilha de Quantidades (PQ)
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Planilha de Quantidades (PQ)
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Planilha de Quantidades (PQ)
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Planilha de Quantidades (PQ)
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Planilha de Quantidades (PQ)
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Planilha de Quantidades (PQ)
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Planilha de Quantidades (PQ)
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Planilha de Quantidades (PQ)
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)
44,O04,Plano de saúde,Vb/mês,254.10,0.0,0.00,0.00,Planilha de Quantidades (PQ)
45,O05,Cesta básica,Vb/mês,326.13,0.0,0.00,0.00,Planilha de Quantidades (PQ)
46,O06,Seguro profissional,Vb/mês,12.55,0.0,0.00,0.00,Planilha de Quantidades (PQ)
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.0,0.00,0.00,Planilha de Quantidades (PQ)
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Planilha de Quantidades (PQ)
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Planilha de Quantidades (PQ)
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Planilha de Quantidades (PQ)
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Planilha de Quantidades (PQ)

🔹 Tabela: As-Built

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.0,0.00,0.00,As-Built
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.00,0.00,As-Built
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.00,0.00,As-Built
3,P04,Engenheiro eletricista,hh,122.13,64.0,0.55,4299.01,As-Built
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,64.0,0.45,3517.37,As-Built
5,P06,Projetista (Cadista),hh,28.53,64.0,0.25,456.41,As-Built
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.00,0.00,As-Built
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.0,0.00,0.00,As-Built
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.00,0.00,As-Built
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,As-Built
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,As-Built
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.00,0.00,As-Built
12,P13,Servente/Auxiliar de obras,hh,15.72,0.0,0.00,0.00,As-Built
13,P14,Supervisor de obras,hh,52.05,0.0,0.00,0.00,As-Built
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,As-Built
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,As-Built
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,As-Built
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,As-Built
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,As-Built
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,As-Built
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,As-Built
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,As-Built
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,As-Built
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,As-Built
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,As-Built
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,As-Built
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,As-Built
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,As-Built
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,As-Built
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,As-Built
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,As-Built
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,As-Built
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,As-Built
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,As-Built
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,As-Built
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,As-Built
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,As-Built
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,As-Built
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,As-Built
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,As-Built
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,As-Built
41,O01,ART,Vb,271.52,0.0,0.00,0.00,As-Built
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,As-Built
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,As-Built
44,O04,Plano de saúde,Vb/mês,254.10,0.0,0.00,0.00,As-Built
45,O05,Cesta básica,Vb/mês,326.13,0.0,0.00,0.00,As-Built
46,O06,Seguro profissional,Vb/mês,12.55,0.0,0.00,0.00,As-Built
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.0,0.00,0.00,As-Built
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.0,0.00,0.00,As-Built
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.0,0.00,0.00,As-Built
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,As-Built
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,As-Built
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,As-Built
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,As-Built

🔹 Tabela: Cabo múltiplo de energia (tetrapolar), condutores flexíveis de cobre (classe 5), classe
de tensão de 0.6/1kV, isolamento de PVC 70ºC, nas cores preto, vermelho e azul e
verde, condutor flexível de cobre nú, capa externa de PVC na cor laranja, retardante à
chama, imune a radiação ultravioleta, Seção 1x4/c # 10.0mm².

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
1,P02,Eletricista de força e controle,hh,35.64,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
2,P03,Ajudante de elétrica,hh,21.21,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
3,P04,Engenheiro eletricista,hh,122.13,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
5,P06,Projetista (Cadista),hh,28.53,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
8,P09,Montador de estruturas metálicas,hh,30.15,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
9,P10,Topógrafo,hh,31.03,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
10,P11,Auxiliar de topografia,hh,16.52,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
11,P12,Sinaleiro de rigger,hh,21.89,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
12,P13,Servente/Auxiliar de obras,hh,15.72,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
13,P14,Supervisor de obras,hh,52.05,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
14,E01,Conteiner escritório,Vb/mês,1700.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
15,E02,Banheiro químico,Vb/mês,1200.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.00,0.0,4.47,"Cabo múltiplo de energia (tetrapolar), conduto..."
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
23,E10,Plano de rigging,Vb,15000.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
24,E11,Linha de vida,Vb,2520.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,1.05,1.0,47.46,"Cabo múltiplo de energia (tetrapolar), conduto..."
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
30,M06,Miscelâneas,Vb,5600.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
31,M07,Água mineral,L,1.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
32,M08,Gelo branco seco,Pct,7.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
33,M09,Garrafa térmica 12 L,und,140.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
34,M11,Estaca de madeira,und,5.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
35,M12,Piquete de madeira,und,3.50,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
36,M13,Tinta - 18L,und,260.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
37,M14,Marcador Industrial,und,16.50,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
38,M15,Estrutura metálica leve,ton,9856.19,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
39,M16,Estrutura metálica média,ton,15425.60,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
40,M17,Estrutura metálica pesada,ton,25019.20,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
41,O01,ART,Vb,271.52,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
42,O02,Exames médicos,Vb,456.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
43,O03,Treinamentos,Vb,426.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
44,O04,Plano de saúde,Vb/mês,254.10,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
45,O05,Cesta básica,Vb/mês,326.13,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
46,O06,Seguro profissional,Vb/mês,12.55,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
50,O10,Combustível G/D,L,6.80,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
51,O11,Água mineral,L,1.05,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
52,O12,Gelo seco,pct,25.60,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."
53,O13,Garrafa térmica,und,220.00,0.00,0.0,0.00,"Cabo múltiplo de energia (tetrapolar), conduto..."

🔹 Tabela: Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 600V, NCM:8536.50.90 CF:5102
MR:ROCKWELL

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
12,P13,Servente/Auxiliar de obras,hh,15.72,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
13,P14,Supervisor de obras,hh,52.05,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,1.0,1.00,230.22,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
44,O04,Plano de saúde,Vb/mês,254.10,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
45,O05,Cesta básica,Vb/mês,326.13,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
46,O06,Seguro profissional,Vb/mês,12.55,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...

🔹 Tabela: Terminal olhal de cobre à compressão #10mm² com furo M8, TM-10-8 da Intelli ou
similar.

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
5,P06,Projetista (Cadista),hh,28.53,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
9,P10,Topógrafo,hh,31.03,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
12,P13,Servente/Auxiliar de obras,hh,15.72,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
13,P14,Supervisor de obras,hh,52.05,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.0,55.87,Terminal olhal de cobre à compressão #10mm² co...
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
23,E10,Plano de rigging,Vb,15000.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
24,E11,Linha de vida,Vb,2520.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,1.0,1.0,5.66,Terminal olhal de cobre à compressão #10mm² co...
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
30,M06,Miscelâneas,Vb,5600.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
31,M07,Água mineral,L,1.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
32,M08,Gelo branco seco,Pct,7.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
34,M11,Estaca de madeira,und,5.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
35,M12,Piquete de madeira,und,3.50,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
36,M13,Tinta - 18L,und,260.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
37,M14,Marcador Industrial,und,16.50,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
41,O01,ART,Vb,271.52,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
42,O02,Exames médicos,Vb,456.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
43,O03,Treinamentos,Vb,426.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
44,O04,Plano de saúde,Vb/mês,254.10,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
45,O05,Cesta básica,Vb/mês,326.13,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
46,O06,Seguro profissional,Vb/mês,12.55,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
50,O10,Combustível G/D,L,6.80,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
51,O11,Água mineral,L,1.05,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
52,O12,Gelo seco,pct,25.60,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...
53,O13,Garrafa térmica,und,220.00,0.0,0.0,0.00,Terminal olhal de cobre à compressão #10mm² co...

🔹 Tabela: Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100Ka T-0, Indicador Frontal 3NE4 101
da Siemens ou similar

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
5,P06,Projetista (Cadista),hh,28.53,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
9,P10,Topógrafo,hh,31.03,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
12,P13,Servente/Auxiliar de obras,hh,15.72,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
13,P14,Supervisor de obras,hh,52.05,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.0,74.50,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
23,E10,Plano de rigging,Vb,15000.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
24,E11,Linha de vida,Vb,2520.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,1.0,1.0,84.66,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
30,M06,Miscelâneas,Vb,5600.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
31,M07,Água mineral,L,1.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
32,M08,Gelo branco seco,Pct,7.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
34,M11,Estaca de madeira,und,5.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
35,M12,Piquete de madeira,und,3.50,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
36,M13,Tinta - 18L,und,260.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
37,M14,Marcador Industrial,und,16.50,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
41,O01,ART,Vb,271.52,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
42,O02,Exames médicos,Vb,456.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
43,O03,Treinamentos,Vb,426.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
44,O04,Plano de saúde,Vb/mês,254.10,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
45,O05,Cesta básica,Vb/mês,326.13,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
46,O06,Seguro profissional,Vb/mês,12.55,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
50,O10,Combustível G/D,L,6.80,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
51,O11,Água mineral,L,1.05,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
52,O12,Gelo seco,pct,25.60,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...
53,O13,Garrafa térmica,und,220.00,0.0,0.0,0.00,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...

🔹 Tabela: Base para Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100Ka, T-0 tipo: 3NH3 230-
0RC da Siemens ou similar

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
5,P06,Projetista (Cadista),hh,28.53,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
9,P10,Topógrafo,hh,31.03,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
12,P13,Servente/Auxiliar de obras,hh,15.72,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
13,P14,Supervisor de obras,hh,52.05,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.0,74.50,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
23,E10,Plano de rigging,Vb,15000.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
24,E11,Linha de vida,Vb,2520.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,1.0,1.0,64.33,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
30,M06,Miscelâneas,Vb,5600.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
31,M07,Água mineral,L,1.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
32,M08,Gelo branco seco,Pct,7.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
34,M11,Estaca de madeira,und,5.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
35,M12,Piquete de madeira,und,3.50,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
36,M13,Tinta - 18L,und,260.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
37,M14,Marcador Industrial,und,16.50,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
41,O01,ART,Vb,271.52,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
42,O02,Exames médicos,Vb,456.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
43,O03,Treinamentos,Vb,426.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
44,O04,Plano de saúde,Vb/mês,254.10,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
45,O05,Cesta básica,Vb/mês,326.13,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
46,O06,Seguro profissional,Vb/mês,12.55,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
50,O10,Combustível G/D,L,6.80,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
51,O11,Água mineral,L,1.05,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
52,O12,Gelo seco,pct,25.60,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...
53,O13,Garrafa térmica,und,220.00,0.0,0.0,0.00,Base para Fusível NH Sitor Ultra Rápido Gr 32A...

🔹 Tabela: Miscelâneas

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.00,0.00,0.00,Miscelâneas
1,P02,Eletricista de força e controle,hh,35.64,0.00,0.00,0.00,Miscelâneas
2,P03,Ajudante de elétrica,hh,21.21,0.00,0.00,0.00,Miscelâneas
3,P04,Engenheiro eletricista,hh,122.13,0.00,0.00,0.00,Miscelâneas
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.00,0.00,0.00,Miscelâneas
5,P06,Projetista (Cadista),hh,28.53,0.00,0.00,0.00,Miscelâneas
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.00,0.00,0.00,Miscelâneas
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.00,0.00,0.00,Miscelâneas
8,P09,Montador de estruturas metálicas,hh,30.15,0.00,0.00,0.00,Miscelâneas
9,P10,Topógrafo,hh,31.03,0.00,0.00,0.00,Miscelâneas
10,P11,Auxiliar de topografia,hh,16.52,0.00,0.00,0.00,Miscelâneas
11,P12,Sinaleiro de rigger,hh,21.89,0.00,0.00,0.00,Miscelâneas
12,P13,Servente/Auxiliar de obras,hh,15.72,0.00,0.00,0.00,Miscelâneas
13,P14,Supervisor de obras,hh,52.05,0.00,0.00,0.00,Miscelâneas
14,E01,Conteiner escritório,Vb/mês,1700.00,0.00,0.00,0.00,Miscelâneas
15,E02,Banheiro químico,Vb/mês,1200.00,0.00,0.00,0.00,Miscelâneas
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.00,0.00,0.00,Miscelâneas
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.00,0.00,0.00,Miscelâneas
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.00,0.03,446.99,Miscelâneas
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.00,0.00,0.00,Miscelâneas
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.00,0.00,0.00,Miscelâneas
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.00,0.00,0.00,Miscelâneas
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.00,0.00,0.00,Miscelâneas
23,E10,Plano de rigging,Vb,15000.00,0.00,0.00,0.00,Miscelâneas
24,E11,Linha de vida,Vb,2520.00,0.00,0.00,0.00,Miscelâneas
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.00,0.00,0.00,Miscelâneas
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.00,0.00,0.00,Miscelâneas
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.00,0.00,0.00,Miscelâneas
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.00,0.00,0.00,Miscelâneas
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.00,0.00,0.00,Miscelâneas
30,M06,Miscelâneas,Vb,5600.00,0.25,1.00,1400.00,Miscelâneas
31,M07,Água mineral,L,1.00,0.00,0.00,0.00,Miscelâneas
32,M08,Gelo branco seco,Pct,7.00,0.00,0.00,0.00,Miscelâneas
33,M09,Garrafa térmica 12 L,und,140.00,0.00,0.00,0.00,Miscelâneas
34,M11,Estaca de madeira,und,5.00,0.00,0.00,0.00,Miscelâneas
35,M12,Piquete de madeira,und,3.50,0.00,0.00,0.00,Miscelâneas
36,M13,Tinta - 18L,und,260.00,0.00,0.00,0.00,Miscelâneas
37,M14,Marcador Industrial,und,16.50,0.00,0.00,0.00,Miscelâneas
38,M15,Estrutura metálica leve,ton,9856.19,0.00,0.00,0.00,Miscelâneas
39,M16,Estrutura metálica média,ton,15425.60,0.00,0.00,0.00,Miscelâneas
40,M17,Estrutura metálica pesada,ton,25019.20,0.00,0.00,0.00,Miscelâneas
41,O01,ART,Vb,271.52,0.00,0.00,0.00,Miscelâneas
42,O02,Exames médicos,Vb,456.00,0.00,0.00,0.00,Miscelâneas
43,O03,Treinamentos,Vb,426.00,0.00,0.00,0.00,Miscelâneas
44,O04,Plano de saúde,Vb/mês,254.10,0.00,0.00,0.00,Miscelâneas
45,O05,Cesta básica,Vb/mês,326.13,0.00,0.00,0.00,Miscelâneas
46,O06,Seguro profissional,Vb/mês,12.55,0.00,0.00,0.00,Miscelâneas
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.00,0.00,0.00,Miscelâneas
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.00,0.00,0.00,Miscelâneas
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.00,0.00,0.00,Miscelâneas
50,O10,Combustível G/D,L,6.80,0.00,0.00,0.00,Miscelâneas
51,O11,Água mineral,L,1.05,0.00,0.00,0.00,Miscelâneas
52,O12,Gelo seco,pct,25.60,0.00,0.00,0.00,Miscelâneas
53,O13,Garrafa térmica,und,220.00,0.00,0.00,0.00,Miscelâneas

🔹 Tabela: Desmontagem do Cabo de Alimentação do Quadro de Distribuição QD-161T-11 até a
Chave Seccionadora 440V no Campo

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.12,1.00,3.60,Desmontagem do Cabo de Alimentação do Quadro d...
1,P02,Eletricista de força e controle,hh,35.64,0.12,1.00,4.28,Desmontagem do Cabo de Alimentação do Quadro d...
2,P03,Ajudante de elétrica,hh,21.21,0.12,1.00,2.55,Desmontagem do Cabo de Alimentação do Quadro d...
3,P04,Engenheiro eletricista,hh,122.13,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
5,P06,Projetista (Cadista),hh,28.53,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
8,P09,Montador de estruturas metálicas,hh,30.15,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
9,P10,Topógrafo,hh,31.03,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
10,P11,Auxiliar de topografia,hh,16.52,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
11,P12,Sinaleiro de rigger,hh,21.89,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
12,P13,Servente/Auxiliar de obras,hh,15.72,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
13,P14,Supervisor de obras,hh,52.05,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
14,E01,Conteiner escritório,Vb/mês,1700.00,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
15,E02,Banheiro químico,Vb/mês,1200.00,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.00,0.00,4.47,Desmontagem do Cabo de Alimentação do Quadro d...
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
23,E10,Plano de rigging,Vb,15000.00,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
24,E11,Linha de vida,Vb,2520.00,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
30,M06,Miscelâneas,Vb,5600.00,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
31,M07,Água mineral,L,1.00,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
32,M08,Gelo branco seco,Pct,7.00,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
33,M09,Garrafa térmica 12 L,und,140.00,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
34,M11,Estaca de madeira,und,5.00,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
35,M12,Piquete de madeira,und,3.50,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
36,M13,Tinta - 18L,und,260.00,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
37,M14,Marcador Industrial,und,16.50,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
38,M15,Estrutura metálica leve,ton,9856.19,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
39,M16,Estrutura metálica média,ton,15425.60,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
40,M17,Estrutura metálica pesada,ton,25019.20,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
41,O01,ART,Vb,271.52,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
42,O02,Exames médicos,Vb,456.00,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
43,O03,Treinamentos,Vb,426.00,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
44,O04,Plano de saúde,Vb/mês,254.10,0.36,0.01,0.52,Desmontagem do Cabo de Alimentação do Quadro d...
45,O05,Cesta básica,Vb/mês,326.13,0.36,0.01,0.67,Desmontagem do Cabo de Alimentação do Quadro d...
46,O06,Seguro profissional,Vb/mês,12.55,0.36,0.01,0.03,Desmontagem do Cabo de Alimentação do Quadro d...
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.36,0.01,0.25,Desmontagem do Cabo de Alimentação do Quadro d...
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.36,0.01,0.90,Desmontagem do Cabo de Alimentação do Quadro d...
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.36,0.01,0.24,Desmontagem do Cabo de Alimentação do Quadro d...
50,O10,Combustível G/D,L,6.80,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
51,O11,Água mineral,L,1.05,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
52,O12,Gelo seco,pct,25.60,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...
53,O13,Garrafa térmica,und,220.00,0.00,0.00,0.00,Desmontagem do Cabo de Alimentação do Quadro d...

🔹 Tabela: Desmontagem da Caixa da Chave Seccionadora 440V no Campo

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,1.26,1.00,37.83,Desmontagem da Caixa da Chave Seccionadora 440...
1,P02,Eletricista de força e controle,hh,35.64,1.26,1.00,44.91,Desmontagem da Caixa da Chave Seccionadora 440...
2,P03,Ajudante de elétrica,hh,21.21,1.26,1.00,26.73,Desmontagem da Caixa da Chave Seccionadora 440...
3,P04,Engenheiro eletricista,hh,122.13,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
5,P06,Projetista (Cadista),hh,28.53,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
8,P09,Montador de estruturas metálicas,hh,30.15,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
9,P10,Topógrafo,hh,31.03,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
10,P11,Auxiliar de topografia,hh,16.52,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
11,P12,Sinaleiro de rigger,hh,21.89,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
12,P13,Servente/Auxiliar de obras,hh,15.72,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
13,P14,Supervisor de obras,hh,52.05,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
14,E01,Conteiner escritório,Vb/mês,1700.00,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
15,E02,Banheiro químico,Vb/mês,1200.00,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.00,0.03,446.99,Desmontagem da Caixa da Chave Seccionadora 440...
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
23,E10,Plano de rigging,Vb,15000.00,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
24,E11,Linha de vida,Vb,2520.00,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
30,M06,Miscelâneas,Vb,5600.00,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
31,M07,Água mineral,L,1.00,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
32,M08,Gelo branco seco,Pct,7.00,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
33,M09,Garrafa térmica 12 L,und,140.00,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
34,M11,Estaca de madeira,und,5.00,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
35,M12,Piquete de madeira,und,3.50,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
36,M13,Tinta - 18L,und,260.00,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
37,M14,Marcador Industrial,und,16.50,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
38,M15,Estrutura metálica leve,ton,9856.19,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
39,M16,Estrutura metálica média,ton,15425.60,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
40,M17,Estrutura metálica pesada,ton,25019.20,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
41,O01,ART,Vb,271.52,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
42,O02,Exames médicos,Vb,456.00,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
43,O03,Treinamentos,Vb,426.00,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
44,O04,Plano de saúde,Vb/mês,254.10,3.78,0.01,5.46,Desmontagem da Caixa da Chave Seccionadora 440...
45,O05,Cesta básica,Vb/mês,326.13,3.78,0.01,7.00,Desmontagem da Caixa da Chave Seccionadora 440...
46,O06,Seguro profissional,Vb/mês,12.55,3.78,0.01,0.27,Desmontagem da Caixa da Chave Seccionadora 440...
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,3.78,0.01,2.60,Desmontagem da Caixa da Chave Seccionadora 440...
48,O08,Alimentação - Almoço,Vb/mês,440.00,3.78,0.01,9.45,Desmontagem da Caixa da Chave Seccionadora 440...
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,3.78,0.01,2.47,Desmontagem da Caixa da Chave Seccionadora 440...
50,O10,Combustível G/D,L,6.80,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
51,O11,Água mineral,L,1.05,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
52,O12,Gelo seco,pct,25.60,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...
53,O13,Garrafa térmica,und,220.00,0.00,0.00,0.00,Desmontagem da Caixa da Chave Seccionadora 440...

🔹 Tabela: Desmontagem da Cortina de Cabos Existente com Trole no Campo

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,16.00,1.00,480.44,Desmontagem da Cortina de Cabos Existente com ...
1,P02,Eletricista de força e controle,hh,35.64,16.00,1.00,570.23,Desmontagem da Cortina de Cabos Existente com ...
2,P03,Ajudante de elétrica,hh,21.21,16.00,1.00,339.39,Desmontagem da Cortina de Cabos Existente com ...
3,P04,Engenheiro eletricista,hh,122.13,0.15,1.00,18.32,Desmontagem da Cortina de Cabos Existente com ...
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.15,1.00,18.32,Desmontagem da Cortina de Cabos Existente com ...
5,P06,Projetista (Cadista),hh,28.53,0.15,1.00,4.28,Desmontagem da Cortina de Cabos Existente com ...
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,16.00,1.00,554.67,Desmontagem da Cortina de Cabos Existente com ...
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,16.00,1.00,680.62,Desmontagem da Cortina de Cabos Existente com ...
8,P09,Montador de estruturas metálicas,hh,30.15,16.00,1.00,482.33,Desmontagem da Cortina de Cabos Existente com ...
9,P10,Topógrafo,hh,31.03,16.00,1.00,496.45,Desmontagem da Cortina de Cabos Existente com ...
10,P11,Auxiliar de topografia,hh,16.52,16.00,1.00,264.24,Desmontagem da Cortina de Cabos Existente com ...
11,P12,Sinaleiro de rigger,hh,21.89,16.00,1.00,350.21,Desmontagem da Cortina de Cabos Existente com ...
12,P13,Servente/Auxiliar de obras,hh,15.72,16.00,1.00,251.56,Desmontagem da Cortina de Cabos Existente com ...
13,P14,Supervisor de obras,hh,52.05,16.00,1.00,832.76,Desmontagem da Cortina de Cabos Existente com ...
14,E01,Conteiner escritório,Vb/mês,1700.00,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
15,E02,Banheiro químico,Vb/mês,1200.00,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.00,0.03,446.99,Desmontagem da Cortina de Cabos Existente com ...
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,1.00,2.00,15705.00,Desmontagem da Cortina de Cabos Existente com ...
23,E10,Plano de rigging,Vb,15000.00,1.00,1.00,15000.00,Desmontagem da Cortina de Cabos Existente com ...
24,E11,Linha de vida,Vb,2520.00,1.00,1.00,2520.00,Desmontagem da Cortina de Cabos Existente com ...
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
30,M06,Miscelâneas,Vb,5600.00,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
31,M07,Água mineral,L,1.00,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
32,M08,Gelo branco seco,Pct,7.00,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
33,M09,Garrafa térmica 12 L,und,140.00,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
34,M11,Estaca de madeira,und,5.00,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
35,M12,Piquete de madeira,und,3.50,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
36,M13,Tinta - 18L,und,260.00,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
37,M14,Marcador Industrial,und,16.50,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
38,M15,Estrutura metálica leve,ton,9856.19,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
39,M16,Estrutura metálica média,ton,15425.60,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
40,M17,Estrutura metálica pesada,ton,25019.20,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
41,O01,ART,Vb,271.52,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
42,O02,Exames médicos,Vb,456.00,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
43,O03,Treinamentos,Vb,426.00,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
44,O04,Plano de saúde,Vb/mês,254.10,176.45,0.01,254.75,Desmontagem da Cortina de Cabos Existente com ...
45,O05,Cesta básica,Vb/mês,326.13,176.45,0.01,326.96,Desmontagem da Cortina de Cabos Existente com ...
46,O06,Seguro profissional,Vb/mês,12.55,176.45,0.01,12.58,Desmontagem da Cortina de Cabos Existente com ...
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,176.45,0.01,121.31,Desmontagem da Cortina de Cabos Existente com ...
48,O08,Alimentação - Almoço,Vb/mês,440.00,176.45,0.01,441.12,Desmontagem da Cortina de Cabos Existente com ...
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,176.45,0.01,115.49,Desmontagem da Cortina de Cabos Existente com ...
50,O10,Combustível G/D,L,6.80,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
51,O11,Água mineral,L,1.05,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
52,O12,Gelo seco,pct,25.60,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...
53,O13,Garrafa térmica,und,220.00,0.00,0.00,0.00,Desmontagem da Cortina de Cabos Existente com ...

🔹 Tabela: Desmontagem da Talha Elétrica 1 Tonelada no Campo

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,48.0,1.00,1441.31,Desmontagem da Talha Elétrica 1 Tonelada no Campo
1,P02,Eletricista de força e controle,hh,35.64,48.0,1.00,1710.69,Desmontagem da Talha Elétrica 1 Tonelada no Campo
2,P03,Ajudante de elétrica,hh,21.21,48.0,1.00,1018.17,Desmontagem da Talha Elétrica 1 Tonelada no Campo
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,48.0,1.00,1664.02,Desmontagem da Talha Elétrica 1 Tonelada no Campo
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,48.0,1.00,2041.85,Desmontagem da Talha Elétrica 1 Tonelada no Campo
8,P09,Montador de estruturas metálicas,hh,30.15,48.0,1.00,1446.98,Desmontagem da Talha Elétrica 1 Tonelada no Campo
9,P10,Topógrafo,hh,31.03,48.0,1.00,1489.35,Desmontagem da Talha Elétrica 1 Tonelada no Campo
10,P11,Auxiliar de topografia,hh,16.52,48.0,1.00,792.72,Desmontagem da Talha Elétrica 1 Tonelada no Campo
11,P12,Sinaleiro de rigger,hh,21.89,48.0,1.00,1050.62,Desmontagem da Talha Elétrica 1 Tonelada no Campo
12,P13,Servente/Auxiliar de obras,hh,15.72,48.0,1.00,754.67,Desmontagem da Talha Elétrica 1 Tonelada no Campo
13,P14,Supervisor de obras,hh,52.05,48.0,1.00,2498.27,Desmontagem da Talha Elétrica 1 Tonelada no Campo
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Desmontagem da Talha Elétrica 1 Tonelada no Campo
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,1.0,6.00,47115.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
23,E10,Plano de rigging,Vb,15000.00,1.0,1.00,15000.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
24,E11,Linha de vida,Vb,2520.00,1.0,1.00,2520.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
44,O04,Plano de saúde,Vb/mês,254.10,528.0,0.01,762.30,Desmontagem da Talha Elétrica 1 Tonelada no Campo
45,O05,Cesta básica,Vb/mês,326.13,528.0,0.01,978.39,Desmontagem da Talha Elétrica 1 Tonelada no Campo
46,O06,Seguro profissional,Vb/mês,12.55,528.0,0.01,37.65,Desmontagem da Talha Elétrica 1 Tonelada no Campo
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,528.0,0.01,363.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
48,O08,Alimentação - Almoço,Vb/mês,440.00,528.0,0.01,1320.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,528.0,0.01,345.60,Desmontagem da Talha Elétrica 1 Tonelada no Campo
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Desmontagem da Talha Elétrica 1 Tonelada no Campo

🔹 Tabela: Desmontagem dos Componentes Internos do Quadro de distribuição QD-161T-11

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,4.0,1.00,120.11,Desmontagem dos Componentes Internos do Quadro...
1,P02,Eletricista de força e controle,hh,35.64,4.0,1.00,142.56,Desmontagem dos Componentes Internos do Quadro...
2,P03,Ajudante de elétrica,hh,21.21,4.0,1.00,84.85,Desmontagem dos Componentes Internos do Quadro...
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,4.0,1.00,170.15,Desmontagem dos Componentes Internos do Quadro...
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
12,P13,Servente/Auxiliar de obras,hh,15.72,4.0,1.00,62.89,Desmontagem dos Componentes Internos do Quadro...
13,P14,Supervisor de obras,hh,52.05,4.0,1.00,208.19,Desmontagem dos Componentes Internos do Quadro...
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Desmontagem dos Componentes Internos do Quadro...
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
44,O04,Plano de saúde,Vb/mês,254.10,24.0,0.01,34.65,Desmontagem dos Componentes Internos do Quadro...
45,O05,Cesta básica,Vb/mês,326.13,24.0,0.01,44.47,Desmontagem dos Componentes Internos do Quadro...
46,O06,Seguro profissional,Vb/mês,12.55,24.0,0.01,1.71,Desmontagem dos Componentes Internos do Quadro...
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,24.0,0.01,16.50,Desmontagem dos Componentes Internos do Quadro...
48,O08,Alimentação - Almoço,Vb/mês,440.00,24.0,0.01,60.00,Desmontagem dos Componentes Internos do Quadro...
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,24.0,0.01,15.71,Desmontagem dos Componentes Internos do Quadro...
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Desmontagem dos Componentes Internos do Quadro...

🔹 Tabela: Desmontagem do Suporte Existente da Chave Seccionadora no Campo

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,2.56,1.00,76.87,Desmontagem do Suporte Existente da Chave Secc...
1,P02,Eletricista de força e controle,hh,35.64,2.56,1.00,91.24,Desmontagem do Suporte Existente da Chave Secc...
2,P03,Ajudante de elétrica,hh,21.21,2.56,1.00,54.30,Desmontagem do Suporte Existente da Chave Secc...
3,P04,Engenheiro eletricista,hh,122.13,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
5,P06,Projetista (Cadista),hh,28.53,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,2.56,1.00,108.90,Desmontagem do Suporte Existente da Chave Secc...
8,P09,Montador de estruturas metálicas,hh,30.15,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
9,P10,Topógrafo,hh,31.03,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
10,P11,Auxiliar de topografia,hh,16.52,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
11,P12,Sinaleiro de rigger,hh,21.89,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
12,P13,Servente/Auxiliar de obras,hh,15.72,2.56,1.00,40.25,Desmontagem do Suporte Existente da Chave Secc...
13,P14,Supervisor de obras,hh,52.05,2.56,1.00,133.24,Desmontagem do Suporte Existente da Chave Secc...
14,E01,Conteiner escritório,Vb/mês,1700.00,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
15,E02,Banheiro químico,Vb/mês,1200.00,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.00,0.03,446.99,Desmontagem do Suporte Existente da Chave Secc...
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
23,E10,Plano de rigging,Vb,15000.00,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
24,E11,Linha de vida,Vb,2520.00,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
30,M06,Miscelâneas,Vb,5600.00,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
31,M07,Água mineral,L,1.00,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
32,M08,Gelo branco seco,Pct,7.00,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
33,M09,Garrafa térmica 12 L,und,140.00,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
34,M11,Estaca de madeira,und,5.00,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
35,M12,Piquete de madeira,und,3.50,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
36,M13,Tinta - 18L,und,260.00,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
37,M14,Marcador Industrial,und,16.50,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
38,M15,Estrutura metálica leve,ton,9856.19,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
39,M16,Estrutura metálica média,ton,15425.60,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
40,M17,Estrutura metálica pesada,ton,25019.20,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
41,O01,ART,Vb,271.52,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
42,O02,Exames médicos,Vb,456.00,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
43,O03,Treinamentos,Vb,426.00,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
44,O04,Plano de saúde,Vb/mês,254.10,15.36,0.01,22.18,Desmontagem do Suporte Existente da Chave Secc...
45,O05,Cesta básica,Vb/mês,326.13,15.36,0.01,28.46,Desmontagem do Suporte Existente da Chave Secc...
46,O06,Seguro profissional,Vb/mês,12.55,15.36,0.01,1.10,Desmontagem do Suporte Existente da Chave Secc...
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,15.36,0.01,10.56,Desmontagem do Suporte Existente da Chave Secc...
48,O08,Alimentação - Almoço,Vb/mês,440.00,15.36,0.01,38.40,Desmontagem do Suporte Existente da Chave Secc...
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,15.36,0.01,10.05,Desmontagem do Suporte Existente da Chave Secc...
50,O10,Combustível G/D,L,6.80,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
51,O11,Água mineral,L,1.05,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
52,O12,Gelo seco,pct,25.60,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...
53,O13,Garrafa térmica,und,220.00,0.00,0.00,0.00,Desmontagem do Suporte Existente da Chave Secc...

🔹 Tabela: Montagem dos Componentes Internos do Quadro de distribuição QD-161T-11

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,4.48,1.00,134.52,Montagem dos Componentes Internos do Quadro de...
1,P02,Eletricista de força e controle,hh,35.64,4.48,1.00,159.66,Montagem dos Componentes Internos do Quadro de...
2,P03,Ajudante de elétrica,hh,21.21,4.48,1.00,95.03,Montagem dos Componentes Internos do Quadro de...
3,P04,Engenheiro eletricista,hh,122.13,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
5,P06,Projetista (Cadista),hh,28.53,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,4.48,1.00,190.57,Montagem dos Componentes Internos do Quadro de...
8,P09,Montador de estruturas metálicas,hh,30.15,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
9,P10,Topógrafo,hh,31.03,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
10,P11,Auxiliar de topografia,hh,16.52,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
11,P12,Sinaleiro de rigger,hh,21.89,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
12,P13,Servente/Auxiliar de obras,hh,15.72,4.48,1.00,70.44,Montagem dos Componentes Internos do Quadro de...
13,P14,Supervisor de obras,hh,52.05,4.48,1.00,233.17,Montagem dos Componentes Internos do Quadro de...
14,E01,Conteiner escritório,Vb/mês,1700.00,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
15,E02,Banheiro químico,Vb/mês,1200.00,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.00,0.03,446.99,Montagem dos Componentes Internos do Quadro de...
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
23,E10,Plano de rigging,Vb,15000.00,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
24,E11,Linha de vida,Vb,2520.00,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
30,M06,Miscelâneas,Vb,5600.00,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
31,M07,Água mineral,L,1.00,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
32,M08,Gelo branco seco,Pct,7.00,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
33,M09,Garrafa térmica 12 L,und,140.00,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
34,M11,Estaca de madeira,und,5.00,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
35,M12,Piquete de madeira,und,3.50,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
36,M13,Tinta - 18L,und,260.00,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
37,M14,Marcador Industrial,und,16.50,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
38,M15,Estrutura metálica leve,ton,9856.19,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
39,M16,Estrutura metálica média,ton,15425.60,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
40,M17,Estrutura metálica pesada,ton,25019.20,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
41,O01,ART,Vb,271.52,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
42,O02,Exames médicos,Vb,456.00,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
43,O03,Treinamentos,Vb,426.00,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
44,O04,Plano de saúde,Vb/mês,254.10,26.88,0.01,38.81,Montagem dos Componentes Internos do Quadro de...
45,O05,Cesta básica,Vb/mês,326.13,26.88,0.01,49.81,Montagem dos Componentes Internos do Quadro de...
46,O06,Seguro profissional,Vb/mês,12.55,26.88,0.01,1.92,Montagem dos Componentes Internos do Quadro de...
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,26.88,0.01,18.48,Montagem dos Componentes Internos do Quadro de...
48,O08,Alimentação - Almoço,Vb/mês,440.00,26.88,0.01,67.20,Montagem dos Componentes Internos do Quadro de...
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,26.88,0.01,17.59,Montagem dos Componentes Internos do Quadro de...
50,O10,Combustível G/D,L,6.80,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
51,O11,Água mineral,L,1.05,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
52,O12,Gelo seco,pct,25.60,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...
53,O13,Garrafa térmica,und,220.00,0.00,0.00,0.00,Montagem dos Componentes Internos do Quadro de...

🔹 Tabela: Montagem do Cabo de Alimentação do Quadro de Distribuição QD-161T-11 até a
Chave Seccionadora 440V no Campo

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.8,1.00,24.02,Montagem do Cabo de Alimentação do Quadro de D...
1,P02,Eletricista de força e controle,hh,35.64,0.8,1.00,28.51,Montagem do Cabo de Alimentação do Quadro de D...
2,P03,Ajudante de elétrica,hh,21.21,0.8,1.00,16.97,Montagem do Cabo de Alimentação do Quadro de D...
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.8,1.00,34.03,Montagem do Cabo de Alimentação do Quadro de D...
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
12,P13,Servente/Auxiliar de obras,hh,15.72,0.8,1.00,12.58,Montagem do Cabo de Alimentação do Quadro de D...
13,P14,Supervisor de obras,hh,52.05,0.8,1.00,41.64,Montagem do Cabo de Alimentação do Quadro de D...
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.00,4.47,Montagem do Cabo de Alimentação do Quadro de D...
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
44,O04,Plano de saúde,Vb/mês,254.10,4.8,0.01,6.93,Montagem do Cabo de Alimentação do Quadro de D...
45,O05,Cesta básica,Vb/mês,326.13,4.8,0.01,8.89,Montagem do Cabo de Alimentação do Quadro de D...
46,O06,Seguro profissional,Vb/mês,12.55,4.8,0.01,0.34,Montagem do Cabo de Alimentação do Quadro de D...
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,4.8,0.01,3.30,Montagem do Cabo de Alimentação do Quadro de D...
48,O08,Alimentação - Almoço,Vb/mês,440.00,4.8,0.01,12.00,Montagem do Cabo de Alimentação do Quadro de D...
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,4.8,0.01,3.14,Montagem do Cabo de Alimentação do Quadro de D...
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Montagem do Cabo de Alimentação do Quadro de D...

🔹 Tabela: Montagem do Suporte Existente da Chave Seccionadora no Campo

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,1.2,1.00,36.03,Montagem do Suporte Existente da Chave Seccion...
1,P02,Eletricista de força e controle,hh,35.64,1.2,1.00,42.77,Montagem do Suporte Existente da Chave Seccion...
2,P03,Ajudante de elétrica,hh,21.21,1.2,1.00,25.45,Montagem do Suporte Existente da Chave Seccion...
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,1.2,1.00,51.05,Montagem do Suporte Existente da Chave Seccion...
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
12,P13,Servente/Auxiliar de obras,hh,15.72,1.2,1.00,18.87,Montagem do Suporte Existente da Chave Seccion...
13,P14,Supervisor de obras,hh,52.05,1.2,1.00,62.46,Montagem do Suporte Existente da Chave Seccion...
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Montagem do Suporte Existente da Chave Seccion...
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
44,O04,Plano de saúde,Vb/mês,254.10,7.2,0.01,10.40,Montagem do Suporte Existente da Chave Seccion...
45,O05,Cesta básica,Vb/mês,326.13,7.2,0.01,13.34,Montagem do Suporte Existente da Chave Seccion...
46,O06,Seguro profissional,Vb/mês,12.55,7.2,0.01,0.51,Montagem do Suporte Existente da Chave Seccion...
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,7.2,0.01,4.95,Montagem do Suporte Existente da Chave Seccion...
48,O08,Alimentação - Almoço,Vb/mês,440.00,7.2,0.01,18.00,Montagem do Suporte Existente da Chave Seccion...
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,7.2,0.01,4.71,Montagem do Suporte Existente da Chave Seccion...
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Montagem do Suporte Existente da Chave Seccion...

🔹 Tabela: Montagem da Caixa da Chave Seccionadora no Campo

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.4,1.00,12.01,Montagem da Caixa da Chave Seccionadora no Campo
1,P02,Eletricista de força e controle,hh,35.64,0.4,1.00,14.26,Montagem da Caixa da Chave Seccionadora no Campo
2,P03,Ajudante de elétrica,hh,21.21,0.4,1.00,8.48,Montagem da Caixa da Chave Seccionadora no Campo
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.4,1.00,17.02,Montagem da Caixa da Chave Seccionadora no Campo
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
12,P13,Servente/Auxiliar de obras,hh,15.72,0.4,1.00,6.29,Montagem da Caixa da Chave Seccionadora no Campo
13,P14,Supervisor de obras,hh,52.05,0.4,1.00,20.82,Montagem da Caixa da Chave Seccionadora no Campo
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Montagem da Caixa da Chave Seccionadora no Campo
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
44,O04,Plano de saúde,Vb/mês,254.10,2.4,0.01,3.46,Montagem da Caixa da Chave Seccionadora no Campo
45,O05,Cesta básica,Vb/mês,326.13,2.4,0.01,4.45,Montagem da Caixa da Chave Seccionadora no Campo
46,O06,Seguro profissional,Vb/mês,12.55,2.4,0.01,0.17,Montagem da Caixa da Chave Seccionadora no Campo
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,2.4,0.01,1.65,Montagem da Caixa da Chave Seccionadora no Campo
48,O08,Alimentação - Almoço,Vb/mês,440.00,2.4,0.01,6.00,Montagem da Caixa da Chave Seccionadora no Campo
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,2.4,0.01,1.57,Montagem da Caixa da Chave Seccionadora no Campo
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Montagem da Caixa da Chave Seccionadora no Campo

🔹 Tabela: Montagem da Talha Elétrica 1 Tonelada do Tipo CTX– Konecranes

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,56.0,1.00,1681.53,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
1,P02,Eletricista de força e controle,hh,35.64,56.0,1.00,1995.80,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
2,P03,Ajudante de elétrica,hh,21.21,56.0,1.00,1187.86,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
3,P04,Engenheiro eletricista,hh,122.13,11.2,1.00,1367.87,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,11.2,1.00,1367.87,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,56.0,1.00,2382.16,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
11,P12,Sinaleiro de rigger,hh,21.89,56.0,1.00,1225.72,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
12,P13,Servente/Auxiliar de obras,hh,15.72,56.0,1.00,880.45,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
13,P14,Supervisor de obras,hh,52.05,56.0,1.00,2914.65,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,7.0,1.00,54967.50,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
23,E10,Plano de rigging,Vb,15000.00,1.0,1.00,15000.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
24,E11,Linha de vida,Vb,2520.00,1.0,1.00,2520.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
44,O04,Plano de saúde,Vb/mês,254.10,414.4,0.01,598.29,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
45,O05,Cesta básica,Vb/mês,326.13,414.4,0.01,767.89,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
46,O06,Seguro profissional,Vb/mês,12.55,414.4,0.01,29.55,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,414.4,0.01,284.90,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
48,O08,Alimentação - Almoço,Vb/mês,440.00,414.4,0.01,1036.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,414.4,0.01,271.24,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Montagem da Talha Elétrica 1 Tonelada do Tipo ...

🔹 Tabela: Montagem da Cortina de Cabos Completo Tipo Festoon com Troles Arrastador

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,24.0,1.00,720.65,Montagem da Cortina de Cabos Completo Tipo Fes...
1,P02,Eletricista de força e controle,hh,35.64,24.0,1.00,855.34,Montagem da Cortina de Cabos Completo Tipo Fes...
2,P03,Ajudante de elétrica,hh,21.21,24.0,1.00,509.08,Montagem da Cortina de Cabos Completo Tipo Fes...
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,24.0,1.00,1020.93,Montagem da Cortina de Cabos Completo Tipo Fes...
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
11,P12,Sinaleiro de rigger,hh,21.89,24.0,1.00,525.31,Montagem da Cortina de Cabos Completo Tipo Fes...
12,P13,Servente/Auxiliar de obras,hh,15.72,24.0,1.00,377.33,Montagem da Cortina de Cabos Completo Tipo Fes...
13,P14,Supervisor de obras,hh,52.05,24.0,1.00,1249.13,Montagem da Cortina de Cabos Completo Tipo Fes...
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Montagem da Cortina de Cabos Completo Tipo Fes...
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
44,O04,Plano de saúde,Vb/mês,254.10,168.0,0.01,242.55,Montagem da Cortina de Cabos Completo Tipo Fes...
45,O05,Cesta básica,Vb/mês,326.13,168.0,0.01,311.31,Montagem da Cortina de Cabos Completo Tipo Fes...
46,O06,Seguro profissional,Vb/mês,12.55,168.0,0.01,11.98,Montagem da Cortina de Cabos Completo Tipo Fes...
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,168.0,0.01,115.50,Montagem da Cortina de Cabos Completo Tipo Fes...
48,O08,Alimentação - Almoço,Vb/mês,440.00,168.0,0.01,420.00,Montagem da Cortina de Cabos Completo Tipo Fes...
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,168.0,0.01,109.96,Montagem da Cortina de Cabos Completo Tipo Fes...
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Montagem da Cortina de Cabos Completo Tipo Fes...

🔹 Tabela: Fornecimento de perfis metálicos leve (< 25kg/m)

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
12,P13,Servente/Auxiliar de obras,hh,15.72,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
13,P14,Supervisor de obras,hh,52.05,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Fornecimento de perfis metálicos leve (< 25kg/m)
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
38,M15,Estrutura metálica leve,ton,9856.19,0.4,1.00,3942.48,Fornecimento de perfis metálicos leve (< 25kg/m)
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
44,O04,Plano de saúde,Vb/mês,254.10,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
45,O05,Cesta básica,Vb/mês,326.13,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
46,O06,Seguro profissional,Vb/mês,12.55,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Fornecimento de perfis metálicos leve (< 25kg/m)

🔹 Tabela: Fornecimento de perfis metálicos médio (> 25kg/m < 80kg/m)

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
1,P02,Eletricista de força e controle,hh,35.64,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
2,P03,Ajudante de elétrica,hh,21.21,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
3,P04,Engenheiro eletricista,hh,122.13,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
5,P06,Projetista (Cadista),hh,28.53,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
8,P09,Montador de estruturas metálicas,hh,30.15,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
9,P10,Topógrafo,hh,31.03,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
10,P11,Auxiliar de topografia,hh,16.52,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
11,P12,Sinaleiro de rigger,hh,21.89,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
12,P13,Servente/Auxiliar de obras,hh,15.72,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
13,P14,Supervisor de obras,hh,52.05,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
14,E01,Conteiner escritório,Vb/mês,1700.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
15,E02,Banheiro químico,Vb/mês,1200.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.00,0.03,446.99,Fornecimento de perfis metálicos médio (> 25kg...
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
23,E10,Plano de rigging,Vb,15000.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
24,E11,Linha de vida,Vb,2520.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
30,M06,Miscelâneas,Vb,5600.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
31,M07,Água mineral,L,1.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
32,M08,Gelo branco seco,Pct,7.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
33,M09,Garrafa térmica 12 L,und,140.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
34,M11,Estaca de madeira,und,5.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
35,M12,Piquete de madeira,und,3.50,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
36,M13,Tinta - 18L,und,260.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
37,M14,Marcador Industrial,und,16.50,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
38,M15,Estrutura metálica leve,ton,9856.19,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
39,M16,Estrutura metálica média,ton,15425.60,0.45,1.00,6941.52,Fornecimento de perfis metálicos médio (> 25kg...
40,M17,Estrutura metálica pesada,ton,25019.20,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
41,O01,ART,Vb,271.52,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
42,O02,Exames médicos,Vb,456.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
43,O03,Treinamentos,Vb,426.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
44,O04,Plano de saúde,Vb/mês,254.10,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
45,O05,Cesta básica,Vb/mês,326.13,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
46,O06,Seguro profissional,Vb/mês,12.55,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
50,O10,Combustível G/D,L,6.80,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
51,O11,Água mineral,L,1.05,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
52,O12,Gelo seco,pct,25.60,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...
53,O13,Garrafa térmica,und,220.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio (> 25kg...

🔹 Tabela: Fornecimento de perfis metálicos médio pesado (> 80kg/m)

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
1,P02,Eletricista de força e controle,hh,35.64,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
2,P03,Ajudante de elétrica,hh,21.21,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
3,P04,Engenheiro eletricista,hh,122.13,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
5,P06,Projetista (Cadista),hh,28.53,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
8,P09,Montador de estruturas metálicas,hh,30.15,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
9,P10,Topógrafo,hh,31.03,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
10,P11,Auxiliar de topografia,hh,16.52,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
11,P12,Sinaleiro de rigger,hh,21.89,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
12,P13,Servente/Auxiliar de obras,hh,15.72,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
13,P14,Supervisor de obras,hh,52.05,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
14,E01,Conteiner escritório,Vb/mês,1700.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
15,E02,Banheiro químico,Vb/mês,1200.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.00,0.03,446.99,Fornecimento de perfis metálicos médio pesado ...
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
23,E10,Plano de rigging,Vb,15000.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
24,E11,Linha de vida,Vb,2520.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
30,M06,Miscelâneas,Vb,5600.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
31,M07,Água mineral,L,1.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
32,M08,Gelo branco seco,Pct,7.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
33,M09,Garrafa térmica 12 L,und,140.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
34,M11,Estaca de madeira,und,5.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
35,M12,Piquete de madeira,und,3.50,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
36,M13,Tinta - 18L,und,260.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
37,M14,Marcador Industrial,und,16.50,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
38,M15,Estrutura metálica leve,ton,9856.19,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
39,M16,Estrutura metálica média,ton,15425.60,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
40,M17,Estrutura metálica pesada,ton,25019.20,0.15,1.00,3752.88,Fornecimento de perfis metálicos médio pesado ...
41,O01,ART,Vb,271.52,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
42,O02,Exames médicos,Vb,456.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
43,O03,Treinamentos,Vb,426.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
44,O04,Plano de saúde,Vb/mês,254.10,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
45,O05,Cesta básica,Vb/mês,326.13,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
46,O06,Seguro profissional,Vb/mês,12.55,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
50,O10,Combustível G/D,L,6.80,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
51,O11,Água mineral,L,1.05,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
52,O12,Gelo seco,pct,25.60,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...
53,O13,Garrafa térmica,und,220.00,0.00,0.00,0.00,Fornecimento de perfis metálicos médio pesado ...

🔹 Tabela: Desmontagem da monovia existente

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,16.0,1.00,480.44,Desmontagem da monovia existente
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.00,0.00,Desmontagem da monovia existente
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.00,0.00,Desmontagem da monovia existente
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.00,0.00,Desmontagem da monovia existente
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.00,0.00,Desmontagem da monovia existente
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Desmontagem da monovia existente
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,16.0,1.00,554.67,Desmontagem da monovia existente
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,16.0,1.00,680.62,Desmontagem da monovia existente
8,P09,Montador de estruturas metálicas,hh,30.15,16.0,1.00,482.33,Desmontagem da monovia existente
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Desmontagem da monovia existente
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Desmontagem da monovia existente
11,P12,Sinaleiro de rigger,hh,21.89,16.0,1.00,350.21,Desmontagem da monovia existente
12,P13,Servente/Auxiliar de obras,hh,15.72,16.0,1.00,251.56,Desmontagem da monovia existente
13,P14,Supervisor de obras,hh,52.05,16.0,1.00,832.76,Desmontagem da monovia existente
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Desmontagem da monovia existente
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Desmontagem da monovia existente
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Desmontagem da monovia existente
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Desmontagem da monovia existente
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Desmontagem da monovia existente
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Desmontagem da monovia existente
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Desmontagem da monovia existente
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Desmontagem da monovia existente
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Desmontagem da monovia existente
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Desmontagem da monovia existente
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Desmontagem da monovia existente
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Desmontagem da monovia existente
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Desmontagem da monovia existente
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Desmontagem da monovia existente
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Desmontagem da monovia existente
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Desmontagem da monovia existente
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Desmontagem da monovia existente
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Desmontagem da monovia existente
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Desmontagem da monovia existente
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Desmontagem da monovia existente
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Desmontagem da monovia existente
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Desmontagem da monovia existente
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Desmontagem da monovia existente
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Desmontagem da monovia existente
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Desmontagem da monovia existente
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Desmontagem da monovia existente
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Desmontagem da monovia existente
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Desmontagem da monovia existente
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Desmontagem da monovia existente
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Desmontagem da monovia existente
44,O04,Plano de saúde,Vb/mês,254.10,112.0,0.01,161.70,Desmontagem da monovia existente
45,O05,Cesta básica,Vb/mês,326.13,112.0,0.01,207.54,Desmontagem da monovia existente
46,O06,Seguro profissional,Vb/mês,12.55,112.0,0.01,7.99,Desmontagem da monovia existente
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,112.0,0.01,77.00,Desmontagem da monovia existente
48,O08,Alimentação - Almoço,Vb/mês,440.00,112.0,0.01,280.00,Desmontagem da monovia existente
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,112.0,0.01,73.31,Desmontagem da monovia existente
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Desmontagem da monovia existente
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Desmontagem da monovia existente
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Desmontagem da monovia existente
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Desmontagem da monovia existente

🔹 Tabela: Desmontagem das estruturas transversais de apoio

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,12.0,1.00,360.33,Desmontagem das estruturas transversais de apoio
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,12.0,1.00,416.01,Desmontagem das estruturas transversais de apoio
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,12.0,1.00,510.46,Desmontagem das estruturas transversais de apoio
8,P09,Montador de estruturas metálicas,hh,30.15,12.0,1.00,361.74,Desmontagem das estruturas transversais de apoio
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
11,P12,Sinaleiro de rigger,hh,21.89,12.0,1.00,262.65,Desmontagem das estruturas transversais de apoio
12,P13,Servente/Auxiliar de obras,hh,15.72,12.0,1.00,188.67,Desmontagem das estruturas transversais de apoio
13,P14,Supervisor de obras,hh,52.05,12.0,1.00,624.57,Desmontagem das estruturas transversais de apoio
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Desmontagem das estruturas transversais de apoio
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
44,O04,Plano de saúde,Vb/mês,254.10,84.0,0.01,121.28,Desmontagem das estruturas transversais de apoio
45,O05,Cesta básica,Vb/mês,326.13,84.0,0.01,155.65,Desmontagem das estruturas transversais de apoio
46,O06,Seguro profissional,Vb/mês,12.55,84.0,0.01,5.99,Desmontagem das estruturas transversais de apoio
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,84.0,0.01,57.75,Desmontagem das estruturas transversais de apoio
48,O08,Alimentação - Almoço,Vb/mês,440.00,84.0,0.01,210.00,Desmontagem das estruturas transversais de apoio
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,84.0,0.01,54.98,Desmontagem das estruturas transversais de apoio
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Desmontagem das estruturas transversais de apoio

🔹 Tabela: Montagem da monovia existente

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,40.0,1.00,1201.09,Montagem da monovia existente
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.00,0.00,Montagem da monovia existente
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.00,0.00,Montagem da monovia existente
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.00,0.00,Montagem da monovia existente
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.00,0.00,Montagem da monovia existente
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Montagem da monovia existente
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,40.0,1.00,1386.69,Montagem da monovia existente
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,40.0,1.00,1701.55,Montagem da monovia existente
8,P09,Montador de estruturas metálicas,hh,30.15,40.0,1.00,1205.82,Montagem da monovia existente
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Montagem da monovia existente
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Montagem da monovia existente
11,P12,Sinaleiro de rigger,hh,21.89,40.0,1.00,875.52,Montagem da monovia existente
12,P13,Servente/Auxiliar de obras,hh,15.72,40.0,1.00,628.89,Montagem da monovia existente
13,P14,Supervisor de obras,hh,52.05,40.0,1.00,2081.89,Montagem da monovia existente
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Montagem da monovia existente
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Montagem da monovia existente
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Montagem da monovia existente
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Montagem da monovia existente
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Montagem da monovia existente
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Montagem da monovia existente
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Montagem da monovia existente
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Montagem da monovia existente
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Montagem da monovia existente
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Montagem da monovia existente
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Montagem da monovia existente
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Montagem da monovia existente
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Montagem da monovia existente
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Montagem da monovia existente
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Montagem da monovia existente
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Montagem da monovia existente
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Montagem da monovia existente
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Montagem da monovia existente
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Montagem da monovia existente
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Montagem da monovia existente
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Montagem da monovia existente
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Montagem da monovia existente
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Montagem da monovia existente
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Montagem da monovia existente
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Montagem da monovia existente
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Montagem da monovia existente
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Montagem da monovia existente
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Montagem da monovia existente
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Montagem da monovia existente
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Montagem da monovia existente
44,O04,Plano de saúde,Vb/mês,254.10,280.0,0.01,404.25,Montagem da monovia existente
45,O05,Cesta básica,Vb/mês,326.13,280.0,0.01,518.84,Montagem da monovia existente
46,O06,Seguro profissional,Vb/mês,12.55,280.0,0.01,19.97,Montagem da monovia existente
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,280.0,0.01,192.50,Montagem da monovia existente
48,O08,Alimentação - Almoço,Vb/mês,440.00,280.0,0.01,700.00,Montagem da monovia existente
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,280.0,0.01,183.27,Montagem da monovia existente
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Montagem da monovia existente
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Montagem da monovia existente
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Montagem da monovia existente
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Montagem da monovia existente

🔹 Tabela: Montagem das estruturas transversais de apoio

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,24.0,1.00,720.65,Montagem das estruturas transversais de apoio
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
5,P06,Projetista (Cadista),hh,28.53,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,24.0,1.00,832.01,Montagem das estruturas transversais de apoio
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,24.0,1.00,1020.93,Montagem das estruturas transversais de apoio
8,P09,Montador de estruturas metálicas,hh,30.15,24.0,1.00,723.49,Montagem das estruturas transversais de apoio
9,P10,Topógrafo,hh,31.03,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
11,P12,Sinaleiro de rigger,hh,21.89,24.0,1.00,525.31,Montagem das estruturas transversais de apoio
12,P13,Servente/Auxiliar de obras,hh,15.72,24.0,1.00,377.33,Montagem das estruturas transversais de apoio
13,P14,Supervisor de obras,hh,52.05,24.0,1.00,1249.13,Montagem das estruturas transversais de apoio
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,1.0,0.03,446.99,Montagem das estruturas transversais de apoio
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
23,E10,Plano de rigging,Vb,15000.00,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
24,E11,Linha de vida,Vb,2520.00,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
30,M06,Miscelâneas,Vb,5600.00,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
31,M07,Água mineral,L,1.00,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
32,M08,Gelo branco seco,Pct,7.00,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
34,M11,Estaca de madeira,und,5.00,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
35,M12,Piquete de madeira,und,3.50,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
36,M13,Tinta - 18L,und,260.00,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
37,M14,Marcador Industrial,und,16.50,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
41,O01,ART,Vb,271.52,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
42,O02,Exames médicos,Vb,456.00,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
43,O03,Treinamentos,Vb,426.00,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
44,O04,Plano de saúde,Vb/mês,254.10,168.0,0.01,242.55,Montagem das estruturas transversais de apoio
45,O05,Cesta básica,Vb/mês,326.13,168.0,0.01,311.31,Montagem das estruturas transversais de apoio
46,O06,Seguro profissional,Vb/mês,12.55,168.0,0.01,11.98,Montagem das estruturas transversais de apoio
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,168.0,0.01,115.50,Montagem das estruturas transversais de apoio
48,O08,Alimentação - Almoço,Vb/mês,440.00,168.0,0.01,420.00,Montagem das estruturas transversais de apoio
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,168.0,0.01,109.96,Montagem das estruturas transversais de apoio
50,O10,Combustível G/D,L,6.80,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
51,O11,Água mineral,L,1.05,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
52,O12,Gelo seco,pct,25.60,0.0,0.00,0.00,Montagem das estruturas transversais de apoio
53,O13,Garrafa térmica,und,220.00,0.0,0.00,0.00,Montagem das estruturas transversais de apoio

🔹 Tabela: nan

,Cód.,Discriminação,Unid,P.Unit,Quant,Futiliz,Custo,Composicao
0,P01,Técnico SSMA,hh,30.03,0.0,0.0,0.0,nan
1,P02,Eletricista de força e controle,hh,35.64,0.0,0.0,0.0,nan
2,P03,Ajudante de elétrica,hh,21.21,0.0,0.0,0.0,nan
3,P04,Engenheiro eletricista,hh,122.13,0.0,0.0,0.0,nan
4,P05,Engenheiro mecânico - Especialista em estrutur...,hh,122.13,0.0,0.0,0.0,nan
5,P06,Projetista (Cadista),hh,28.53,0.0,0.0,0.0,nan
6,P07,Alpinista industrial (Montador de andaime),hh,34.67,0.0,0.0,0.0,nan
7,P08,Encarregado de elétrica ou andaimes,hh,42.54,0.0,0.0,0.0,nan
8,P09,Montador de estruturas metálicas,hh,30.15,0.0,0.0,0.0,nan
9,P10,Topógrafo,hh,31.03,0.0,0.0,0.0,nan
10,P11,Auxiliar de topografia,hh,16.52,0.0,0.0,0.0,nan
11,P12,Sinaleiro de rigger,hh,21.89,0.0,0.0,0.0,nan
12,P13,Servente/Auxiliar de obras,hh,15.72,0.0,0.0,0.0,nan
13,P14,Supervisor de obras,hh,52.05,0.0,0.0,0.0,nan
14,E01,Conteiner escritório,Vb/mês,1700.00,0.0,0.0,0.0,nan
15,E02,Banheiro químico,Vb/mês,1200.00,0.0,0.0,0.0,nan
16,E03,"Tenda lonada 6 x 6 m, piramidal - AQUISIÇÃO",Vb,4500.00,0.0,0.0,0.0,nan
17,E04,Mobiliário (Cadeiras e mesas plásticas),Vb,852.46,0.0,0.0,0.0,nan
18,E05,Veículo de Locação - Fiat Ducato Minibus Luxo ...,Vb/mês,15852.96,0.0,0.0,0.0,nan
19,E06,Nível DSZ automático com bolha,Vb/Mês,275.00,0.0,0.0,0.0,nan
20,E07,Estação total Kit GD2i-8,Vb/Mês,1250.00,0.0,0.0,0.0,nan
21,E08,Receptor GNSS RTKCHC i50,Vb/Mês,1750.00,0.0,0.0,0.0,nan
22,E09,Guindaste c/operador 30 ton,Diária,7852.50,0.0,0.0,0.0,nan
23,E10,Plano de rigging,Vb,15000.00,0.0,0.0,0.0,nan
24,E11,Linha de vida,Vb,2520.00,0.0,0.0,0.0,nan
25,M01,"Cabo múltiplo de energia (tetrapolar), conduto...",M,45.20,0.0,0.0,0.0,nan
26,M02,Chave seccionadora 30A TYPE 3R/4/12 CLAS S H 6...,UND,230.22,0.0,0.0,0.0,nan
27,M03,Terminal olhal de cobre à compressão #10mm² co...,UND,5.66,0.0,0.0,0.0,nan
28,M04,Fusível NH Sitor Ultra Rápido Gr 32A 1000V 100...,UND,84.66,0.0,0.0,0.0,nan
29,M05,Base para Fusível NH Sitor Ultra Rápido Gr 32A...,UND,64.33,0.0,0.0,0.0,nan
30,M06,Miscelâneas,Vb,5600.00,0.0,0.0,0.0,nan
31,M07,Água mineral,L,1.00,0.0,0.0,0.0,nan
32,M08,Gelo branco seco,Pct,7.00,0.0,0.0,0.0,nan
33,M09,Garrafa térmica 12 L,und,140.00,0.0,0.0,0.0,nan
34,M11,Estaca de madeira,und,5.00,0.0,0.0,0.0,nan
35,M12,Piquete de madeira,und,3.50,0.0,0.0,0.0,nan
36,M13,Tinta - 18L,und,260.00,0.0,0.0,0.0,nan
37,M14,Marcador Industrial,und,16.50,0.0,0.0,0.0,nan
38,M15,Estrutura metálica leve,ton,9856.19,0.0,0.0,0.0,nan
39,M16,Estrutura metálica média,ton,15425.60,0.0,0.0,0.0,nan
40,M17,Estrutura metálica pesada,ton,25019.20,0.0,0.0,0.0,nan
41,O01,ART,Vb,271.52,0.0,0.0,0.0,nan
42,O02,Exames médicos,Vb,456.00,0.0,0.0,0.0,nan
43,O03,Treinamentos,Vb,426.00,0.0,0.0,0.0,nan
44,O04,Plano de saúde,Vb/mês,254.10,0.0,0.0,0.0,nan
45,O05,Cesta básica,Vb/mês,326.13,0.0,0.0,0.0,nan
46,O06,Seguro profissional,Vb/mês,12.55,0.0,0.0,0.0,nan
47,O07,Alimentação - Café da manhã,Vb/mês,121.00,0.0,0.0,0.0,nan
48,O08,Alimentação - Almoço,Vb/mês,440.00,0.0,0.0,0.0,nan
49,O09,Ferramentas para mão de obra,Vb/mês,115.20,0.0,0.0,0.0,nan
50,O10,Combustível G/D,L,6.80,0.0,0.0,0.0,nan
51,O11,Água mineral,L,1.05,0.0,0.0,0.0,nan
52,O12,Gelo seco,pct,25.60,0.0,0.0,0.0,nan
53,O13,Garrafa térmica,und,220.00,0.0,0.0,0.0,nan